### ISSUE TITLE
Custom validation, translations

### ISSUE THREAD

**Issue by sehmaschine** [vsimko/node-graphql-constraint-lambda#2]
I've followed the link from https://github.com/prisma/prisma/issues/728 and this package looks useful indeed.

A couple of questions though:
1. Can we use custom validation functions?
2. How is it possible to translate the error messages?

With my usecase it is required to customize the error messages with certain fields. E.g. field `primaryEmail` should have another error message compared with `secondaryEmail`. So I need to define the error message per field. Maybe this could be implemented with a future version.
Depending on the project, a validation with `contains` could require a very specific error message as well.

**Comment by vsimko** [comment]
This makes perfectly sense. In the initial version, I focused on basic functionality and tried to keep the code concise, therefore there is no customization possible. However, I'm planning to implement such a configuration in future. Here is my proposal:

I would like to keep default configuration easy to use:
```js
const { constriant } = require('node-graphql-constraint-lambda')
// this would provide a pre-configured directive
```

The user would be able to provide own format2fun mapping and custom mapping for error messages.
For this, there will be a higher-order function `prepareConstraintDirective` that returns a configured `constriant` function.

```js
const { prepareConstraintDirective } = require('node-graphql-constraint-lambda')
const constraint = prepareConstriantDirective(customFormat2Fun, customMessages)
```

**Comment by vsimko** [comment]
I implemented the customization API. It is now possible to customize error messages as well as validators.
The description is in `README.md`
